config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(task_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def show
    @flat = Flat.find(params[:id])
  end

  private

  def task_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <div class=flat>
    <ul class="list-group">
      <% @flats.each do |flat| %>
        <p class="list-group-item"><%= flat.name %></p>
        <p class="list-group-item"><%= flat.address %></p>
        <p class="list-group-item"><%= flat.description %></p>
        <p class="list-group-item"><%= flat.price_per_night %></p>
        <p class="list-group-item"><%= flat.number_of_guests %></p>
      <% end %>
    </ul>
  </div>
</div>

<button><%= link_to 'Upload a new flat', new_flat_path %></button>

app/views/flats/new.html.erb
<%= form_for(@flat) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :description%>
  <%= f.text_field :description%>
  <%= f.label :price_per_night%>
  <%= f.number_field :price_per_night%>
  <%= f.label :number_of_guests%>
  <%= f.number_field :number_of_guests%>
  <%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<p><%= @flat.name %></p>
<p><%= @flat.address %></p>
<p><%= @flat.description %></p>
<p><%= @flat.price_per_night %></p>
<p><%= @flat.number_of_guests %></p>


<%= link_to("Back to home page", flats_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>